import { createServerFn } from '@tanstack/react-start'
import { auth } from '@clerk/tanstack-react-start/server'

export const uploadListingImageFn = createServerFn({ method: 'POST' }).handler(
  async (ctx: any) => {
    const data = ctx.data as { fileBase64: string; fileName: string; mimeType: string }
    const { userId } = await auth()
    
    if (!userId) {
      throw new Error('Unauthorized')
    }

    try {
      const apiKey = process.env.VITE_IMGBB_API_KEY
      if (!apiKey) throw new Error('ImgBB API key is missing from environment variables')

      const formData = new FormData()
      formData.append('image', data.fileBase64)
      
      const response = await fetch(`https://api.imgbb.com/1/upload?key=${apiKey}`, {
        method: 'POST',
        body: formData
      })
      
      if (!response.ok) {
        throw new Error(`ImgBB API error: ${response.statusText}`)
      }
      
      const result = await response.json()
      
      if (!result.success) {
        throw new Error(result.error?.message || 'ImgBB upload failed')
      }

      // Return the public URL generated by ImgBB
      return result.data.url
      
    } catch (error: any) {
      console.error('[uploadListingImageFn] Failed to upload image via ImgBB:', error)
      throw new Error(error.message || 'Image upload failed')
    }
  }
)
