/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicJoinFarmerRouteImport } from './routes/_public/join-farmer'
import { Route as ProtectedFarmerRouteImport } from './routes/_protected/farmer'
import { Route as ProtectedBuyerRouteImport } from './routes/_protected/buyer'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as AuthSsoCallbackRouteImport } from './routes/_auth/sso-callback'
import { Route as AuthSignOutRouteImport } from './routes/_auth/sign-out'
import { Route as ApiOgRouteImport } from './routes/_api/og'
import { Route as AuthSignUpSplatRouteImport } from './routes/_auth/sign-up.$'
import { Route as AuthSignInSplatRouteImport } from './routes/_auth/sign-in.$'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicJoinFarmerRoute = PublicJoinFarmerRouteImport.update({
  id: '/join-farmer',
  path: '/join-farmer',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedFarmerRoute = ProtectedFarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBuyerRoute = ProtectedBuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSsoCallbackRoute = AuthSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthRoute,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/_api/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpSplatRoute = AuthSignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInSplatRoute = AuthSignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/og': typeof ApiOgRoute
  '/sign-out': typeof AuthSignOutRoute
  '/sso-callback': typeof AuthSsoCallbackRoute
  '/admin': typeof ProtectedAdminRoute
  '/buyer': typeof ProtectedBuyerRoute
  '/farmer': typeof ProtectedFarmerRoute
  '/join-farmer': typeof PublicJoinFarmerRoute
  '/': typeof PublicIndexRoute
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
}
export interface FileRoutesByTo {
  '/og': typeof ApiOgRoute
  '/sign-out': typeof AuthSignOutRoute
  '/sso-callback': typeof AuthSsoCallbackRoute
  '/admin': typeof ProtectedAdminRoute
  '/buyer': typeof ProtectedBuyerRoute
  '/farmer': typeof ProtectedFarmerRoute
  '/join-farmer': typeof PublicJoinFarmerRoute
  '/': typeof PublicIndexRoute
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_api/og': typeof ApiOgRoute
  '/_auth/sign-out': typeof AuthSignOutRoute
  '/_auth/sso-callback': typeof AuthSsoCallbackRoute
  '/_protected/admin': typeof ProtectedAdminRoute
  '/_protected/buyer': typeof ProtectedBuyerRoute
  '/_protected/farmer': typeof ProtectedFarmerRoute
  '/_public/join-farmer': typeof PublicJoinFarmerRoute
  '/_public/': typeof PublicIndexRoute
  '/_auth/sign-in/$': typeof AuthSignInSplatRoute
  '/_auth/sign-up/$': typeof AuthSignUpSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/og'
    | '/sign-out'
    | '/sso-callback'
    | '/admin'
    | '/buyer'
    | '/farmer'
    | '/join-farmer'
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/og'
    | '/sign-out'
    | '/sso-callback'
    | '/admin'
    | '/buyer'
    | '/farmer'
    | '/join-farmer'
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_public'
    | '/_api/og'
    | '/_auth/sign-out'
    | '/_auth/sso-callback'
    | '/_protected/admin'
    | '/_protected/buyer'
    | '/_protected/farmer'
    | '/_public/join-farmer'
    | '/_public/'
    | '/_auth/sign-in/$'
    | '/_auth/sign-up/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiOgRoute: typeof ApiOgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/join-farmer': {
      id: '/_public/join-farmer'
      path: '/join-farmer'
      fullPath: '/join-farmer'
      preLoaderRoute: typeof PublicJoinFarmerRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/farmer': {
      id: '/_protected/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof ProtectedFarmerRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/buyer': {
      id: '/_protected/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof ProtectedBuyerRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/sso-callback': {
      id: '/_auth/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof AuthSsoCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-out': {
      id: '/_auth/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_api/og': {
      id: '/_api/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up/$': {
      id: '/_auth/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof AuthSignUpSplatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in/$': {
      id: '/_auth/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof AuthSignInSplatRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignOutRoute: typeof AuthSignOutRoute
  AuthSsoCallbackRoute: typeof AuthSsoCallbackRoute
  AuthSignInSplatRoute: typeof AuthSignInSplatRoute
  AuthSignUpSplatRoute: typeof AuthSignUpSplatRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignOutRoute: AuthSignOutRoute,
  AuthSsoCallbackRoute: AuthSsoCallbackRoute,
  AuthSignInSplatRoute: AuthSignInSplatRoute,
  AuthSignUpSplatRoute: AuthSignUpSplatRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRoute
  ProtectedBuyerRoute: typeof ProtectedBuyerRoute
  ProtectedFarmerRoute: typeof ProtectedFarmerRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRoute,
  ProtectedBuyerRoute: ProtectedBuyerRoute,
  ProtectedFarmerRoute: ProtectedFarmerRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicJoinFarmerRoute: typeof PublicJoinFarmerRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicJoinFarmerRoute: PublicJoinFarmerRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiOgRoute: ApiOgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
